kubevirt/kubevirt-velero-plugin

Makefile

as stated in the title
Fixes #
```release-note
NONE
```

Fix make push dependency

---

README.md
example/datavolume.yaml
example/vm.yaml
hack/build/release-description.sh
main.go

Update README and release-notes script
Fixes #
```release-note
NONE
```

Update README and release-notes script

---

tests/dv_backup_test.go
tests/framework/framework.go
tests/resource_filtering_test.go
tests/utils.go
tests/vm_backup_test.go

Extracted variables so the test names can be configured.
Fixes #
```release-note
NONE
```

Make tests more universal

---

hack/release.sh
pkg/plugin/pod_restore_item_action.go

Add test binary to release artifacts, so it is easier to grab the binary and run tests
Fixes #
```release-note
NONE
```

Release test bin

---

tests/dv_backup_test.go
tests/framework/framework.go
tests/utils.go

This is a follow up to https://github.com/kubevirt/kubevirt-velero-plugin/pull/25. One Variable was missing the S3 Region.
Fixes #
```release-note
NONE
```

S3 Region extraced to ENV

---

tests/vm_backup_test.go

On Wffc storage the DV will not be populated until VM start is attempted.
After the change VM always starts in BeforeEach, and only when testing stopped VM's it is stopped in the test.
Fixes #
```release-note
NONE
```

Correct vm test to run on WFFC storage

---

hack/release.sh

Fix typo in release script and also add missing artifacts
Fixes #
```release-note
NONE
```

Fix typo in release script

---

hack/run-ci.sh

Fixes #
```release-note
NONE
```

Emit junit report in artifacts dir

---

tests/dv_backup_test.go
tests/resource_filtering_test.go
tests/vm_backup_test.go

Series of tests that can be run on external clusters. 
There is a plan to test all tests. Right now this is a selected small group of most important tests. 
Fixes #
```release-note
NONE
```

Select some tests as a core

---

hack/build/run-functional-tests.sh

makes it possible to run func tests without running
make cluster-up
Fixes #
```release-note
NONE
```

Simplify KUBECONFIG for tests

---

tests/resource_filtering_test.go
tests/utils.go
tests/vm_backup_test.go

Storage class used in vm tests
Fixes #
```release-note
NONE
```

Storage class used in vm tests

---

tests/resource_filtering_test.go
tests/vm_backup_test.go

k8s objects might be modified by other entities, so in case
of error update needs to be retried.
Also removed one test from smoke group
Fixes #
```release-note
NONE
```

Update objects in loop

---

Makefile

Add a few targets to make it possible to build code and test binary and also run functional tests locally.
Fixes #
```release-note
NONE
```

Make local builds

---

Makefile
tests/resource_filtering_test.go

Fixes #
```release-note
NONE
```

Use builder from quay

---

Makefile

Fixes #
```release-note
NONE
```

Correct directory name

---

tests/resource_filtering_test.go

Retry when updating the object. Sometimes the original object might change between
the fetch and update steps so it is ok to retry at least once.
Fixes #
https://github.com/kubevirt/kubevirt-velero-plugin/issues/57
```release-note
NONE
```

Correct test flakiness

---

tests/resource_filtering_test.go

Update the remaining SKIPPED tests to reflect the desired behavior 
Fixes #
```release-note
NONE
```

Update some tests that are currently skipped, so they can run

---

tests/resource_filtering_test.go
tests/utils.go

Adds a verification steps to make sure the PVC is restored
and not re-imported. Also delete VM in foreground, so it waits
for all dependent objects to also disappear.
Fixes #
```release-note
NONE
```

Verify PVC by writing a file

---

hack/velero/deploy-velero.sh
tests/dv_backup_test.go
tests/utils.go
tests/vm_backup_test.go

Snapshot location is actually not needed in the tests. Snapshot location
can and should be configured when running on a storage provider that
has an option to store snapshot in configurable locations. This is not
possible on ceph provider used in functional tests, which stores snapshots
in the same location as normal volumes.
Fixes #
```release-note
NONE
```

Correct snapshot location configuration

---

hack/build/build-functest.sh
tests/dv_backup_test.go
tests/framework/backup.go
tests/framework/storage.go
tests/framework/vm.go
tests/resource_filtering_test.go
tests/utils.go
tests/vm_backup_test.go

tests: Cleanup - move common code

---

tests/resource_filtering_test.go

Correct Paused VM test to exlude pod (as described) and add a new negative test for backup up a paused VM. 
Fixes #
```release-note
```

Update test for paused VM

---

OWNERS_ALIASES

Add @ShellyKa13 as an approver
Fixes #
```release-note
NONE
```

Add new approver

---

hack/config.sh
tests/framework/backup.go
tests/framework/framework.go
tests/framework/storage.go
tests/framework/vm.go
tests/resource_filtering_test.go

Improve test logs
Fixes #
```release-note
NONE
```

Improve test logs

---

tests/vm_backup_test.go

Signed-off-by: Shelly Kagan <skagan@redhat.com>
Fixes #
```release-note
```

Fix bug of not initializing global vm

---

tests/dv_backup_test.go
tests/resource_filtering_test.go

Signed-off-by: dalia-frank <dafrank@redhat.com>
Fixes #
```release-note
NONE
```

add test id

---

hack/cluster-deploy-prerequisites.sh
pkg/plugin/dv_backup_item_action.go
pkg/plugin/vm_backup_item_action_test.go
pkg/plugin/vmi_backup_item_action_test.go
pkg/util/util.go
pkg/util/util_test.go
tests/dv_backup_test.go
tests/framework/matcher/helper.go
tests/framework/matcher/phase.go
tests/framework/storage.go
tests/framework/vm.go
tests/resource_filtering_test.go
tests/vm_backup_test.go

Fixes #
```release-note
Adjust plugin to run with Datavolume garbage collection
```

Adjust plugin and tests to run with Data volume GC

---

Makefile

Fixes #
```release-note
NONE
```

Match builder image with project go version

---

tests/resource_filtering_test.go
tests/vm_backup_test.go

Add test ID's
Fixes #
```release-note
NONE
```

Add tests ids

---

hack/config.sh
tests/framework/backup.go
tests/resource_filtering_test.go
tests/vm_backup_test.go

Velero 1.12 was released recently and of course it broke some tests
Fixes #
```release-note
NONE
```

Update velero 1.12 and fix tests

---

hack/config.sh

Fixes #
```release-note
Update velero version 1.13.0 update velero-plugin-for-csi 0.7.0
```

Update velero and velero-plugin-for-csi to latest 1.13.0 and 0.7

---

tests/framework/storage.go
tests/resource_filtering_test.go
tests/utils.go

DockerHub is rate limiting, so at some point pulling this will simply fail.
Fixes #
```release-note
NONE
```

Get rid of busybox dockerhub image usage in tests

---

hack/config.sh

watch for the following to land
https://github.com/openshift/oadp-operator/pull/1349

oadp update

---

OWNERS_ALIASES

Fixes #
```release-note
NONE
```

Owners: add alromero as approver and reviewer

---

README.md

Update Velero plugins doc link to latest

---

README.md

Update Velero plugins doc link to 1.14

---

README.md

Update Velero plugins doc link to 1.12

---

pkg/plugin/vm_backup_item_action.go

/cc @ShellyKa13 
/cc @alromeros 
Follow up to https://github.com/kubevirt/kubevirt-velero-plugin/pull/333#discussion_r2042434559
Fixes #
```release-note
NONE
```

chore(vm_backup): Add comment about Velero status restore behaviour
