kubevirt/kubevirt-velero-plugin

pkg/plugin/dv_backup_item_action.go, pkg/plugin/dv_backup_item_action_test.go, pkg/plugin/pod_restore_item_action.go, pkg/plugin/vm_backup_item_action.go, pkg/plugin/vm_backup_item_action_test.go, pkg/plugin/vm_restore_item_action.go, pkg/plugin/vmi_backup_item_action.go, pkg/plugin/vmi_backup_item_action_test.go, pkg/plugin/vmi_restore_item_action.go, pkg/util/util.go, pkg/util/util_test.go, tests/resource_filtering_test.go, tests/utils.go
Velero provides a number of options for resource filtering for excluding
objects from backups:
*  –exclude-namespaces
*  –exclude-resources
*  velero.io/exclude-from-backup=true
This PR covers all work required to support all of them.
Signed-off-by: Tomasz Baranski <tbaransk@redhat.com>
Fixes #
```release-note
NONE
```
=> Support resource exclusion

go.mod, go.sum, tests/framework/framework.go, tests/reporters/reporters.go, tests/tests_suite_test.go, vendor/kubevirt.io/qe-tools/LICENSE, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go, vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go, vendor/modules.txt
Log velero backup and restore objects and also the pod logs (especially velero pod logs might be interesting). 
Additionally adds a Junit reporter which might be used by PROW to better show failed/skipped tests.
Fixes #
```release-note
NONE
```
=> Log velero backup and restore in tests

tests/resource_filtering_test.go
Make sure that backup and restore has unique name for each test,
and that all backups are removed after tests.
Make sure that backup and restore has unique name for each test,
and that all backups are removed after tests.
Fixes #
```release-note
NONE
```
=> Improve test cleanup and isolation

tests/dv_backup_test.go, tests/utils.go
Fixes #
```release-note
NONE
```
=> DV test can now run on WFFC storage

tests/dv_backup_test.go, tests/framework/framework.go, tests/resource_filtering_test.go, tests/utils.go
Adds KVP_STORAGECLASS variable. This environment variable can be set to select which storage class will be used by DataVolumes created in tests.
Fixes #
```release-note
NONE
```
=> STORAGECLASS enironment variable

hack/build/build-functest.sh
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>
Different builder images vary in setup so adjust ourselves
to be able to get ginkgo binary regardless.
Fixes #
```release-note
NONE
```
=> Grab exact path of ginkgo binary

tests/resource_filtering_test.go, tests/utils.go
Change big 5Gig fedora image to smaller 1Gig alpine. 
Fixes #
Just checking if tests are faster and more predictable. 
```release-note
NONE
```
=> Use smaller alpine in tests

main.go, pkg/plugin/dv_backup_item_action.go, pkg/plugin/dv_backup_item_action_test.go, pkg/plugin/pvc_restore_item_action.go, pkg/plugin/pvc_restore_item_action_test.go, pkg/util/util.go, tests/dv_backup_test.go, tests/utils.go
When the "not finished DataVolume" is stored in backup it should restore correctly and CDI shoud retry the DV action to finish it.
DataVolume is stored as is, without applying "PrePopulated" annotation. The PVC for this DV is stored and marked InProgress, then it is not restored (skipped). 
Fixes #
Currently it is not possible to skip a PVC during backup. 
```release-note
Handle DV that is in progress
```
=> Handle DV that is in progress 

tests/utils.go, tests/vm_backup_test.go
Test failed:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt-velero-plugin/75/pull-kvp-functional-test/1562787451645202432
This PR improves logging for troubleshooting.
Fixes #
```release-note
NONE
```
=> Simplify test and improve test logging

hack/build/run-functional-tests.sh, hack/config.sh, hack/velero/add-plugin.sh, hack/velero/deploy-velero.sh, hack/velero/remove-plugin.sh, hack/velero/undeploy-velero.sh
Previously velero binary was stored in source control. Now, the script can fetch velero version directly from release page.
Fixes #
```release-note
NONE
```
=> Do not store velero as a blob

Makefile
Fixes issue mentioned on https://github.com/kubevirt/project-infra/pull/2370
Kinda unnecessary, you really have to [go out of your way to use rootless podman now](https://github.com/kubevirt/kubevirtci/pull/833), but it was easy to check for.
```release-note
NONE
```
=> Only use --userns=keep-id for rootless podman

hack/build/releases.md
This is based of the cdi release doc
https://github.com/kubevirt/containerized-data-importer/blob/main/doc/releases.md.
Documents steps needed to release a plugin.
Fixes #
```release-note
NONE
```
=> Release doc

pkg/util/util.go, pkg/util/util_test.go
Signed-off-by: menyakun <lxs137@hotmail.com>
Fixes #132 
user could specific full resource name, such as "virtualmachines.kubevirt.io", should be backed up
```release-note
Consider excludeded resources by its full name
```
=> bugfix: should consider excludeded resources by its full name

hack/config.sh, tests/resource_filtering_test.go
This corresponds with downstream OADP for 4.14
Velero 1.12.0 is too new for downstream testing.
Fixes #
```release-note
Use velero 1.9.4
```
=> [release-v0.6] Use Velero 1.9.4

hack/config.sh, tests/resource_filtering_test.go
Use velero version 1.12 for 0.6 plugin version
Fixes #
```release-note
Use velero 1.12.Z for 0.6 release
```
=> [release-v0.6] update velero back to 1.12.Z also update velero-plugin-for-csi to match the velero version

.gitignore, README.md, cmd/template-script-backup-restore/template-script-backup-restore.sh, cmd/velero-backup-restore/velero-backup-restore.sh, hack/build/build-functest.sh, hack/build/run-functional-tests.sh, partner-compatibility-testing.md, tests/framework/externalBackup.go, tests/framework/framework.go, tests/resource_filtering_test.go, tests/tests_suite_test.go, tests/vm_backup_test.go
Generalize tests marked with label PartnerComp to run with configured script used to backup and restore.
Added documentation for backup partner explaining what needs to be done in order to run the tests with their backup solution.
Added a script for Velero.
Fixes #
```release-note
Backup partner compatibility testing framework
```
=> Add backup partner compatibility testing framework

pkg/plugin/pod_restore_item_action.go, pkg/plugin/pod_restore_item_action_test.go
Once the vm is started the hotplug process will
create the pod as needed.
No need to restore the hotplug pod, it will be recreated once the disk will be hotplugged when the vm is running.
Fixes #
```release-note
Skip restore hotplug pod
```
=> Skip restoring hotplug pod

cmd/velero-backup-restore/velero-backup-restore.sh, pkg/plugin/vm_backup_item_action.go, tests/framework/kubectl.go, tests/framework/manifests_utils.go, tests/manifests/cluster-instancetype.yaml, tests/manifests/cluster-preference.yaml, tests/manifests/vm_with_clusterinstancetype_and_clusterpreference.yaml, tests/vm_backup_test.go
Support `VirtualMachineClusterInstancetype` and `VirtualMachineClusterpreference`
Also better support namespaced versions by doing case insensitive check of `vm.spec.instancetype|preference.kind` 
Fixes #258
```release-note
Support VirtualMachineClusterInstancetype and VirtualMachineClusterPreference
```
=> Support VirtualMachineClusterInstancetype and VirtualMachineClusterPreference

tests/framework/backup.go
Incase of error in getting the backup we exited the poll. Instead we should print the error and try polling again the error might be temporary.
Fixes #
```release-note
NONE
```
=> tests: Fix poll of backup phase

pkg/plugin/vmi_backup_item_action.go, pkg/plugin/vmi_backup_item_action_test.go, tests/resource_filtering_test.go
**What this PR does / why we need it**: 
This Pull Request aims to update the backup process for VMIs so that when the VMI is owned by a VM excluded from the backup, we also exclude the VMI without triggering an error.
Fixes # https://issues.redhat.com/browse/CNV-45094
```release-note
Bugfix: Ignore VMIs from backup when owner VM is excluded
```
=> Ignore VMIs from backup when owner VMs are excluded

pkg/plugin/vm_backup_item_action.go, pkg/plugin/vm_backup_item_action_test.go, pkg/plugin/vmi_backup_item_action.go, pkg/plugin/vmi_backup_item_action_test.go
This Pull Request aims to implement the `MetadataBackup` label, which allows to bypass restore-specific checks during backup.
This feature allows safely backing up resources such as VirtualMachines and VirtualMachineInstances even when restore conditions are not met, such as when DVs or PVCs are excluded from the backup.
Fixes # https://github.com/kubevirt/kubevirt-velero-plugin/issues/259
Feel free to discuss/oppose the annotation approach. I think this is the cleanest way to ignore restore checks for a specific object, but we may consider other …
=> Allow skipping restore-specific checks during backup

tests/framework/framework.go
The dump function dumped backups also for restores
Fixes #
```release-note
NONE
```
=> Fix report of velero restores

example/vm.yaml, tests/framework/vm.go, tests/manifests/vm_for_hotplug.yaml, tests/manifests/vm_with_access_credentials.yaml, tests/manifests/vm_with_clusterinstancetype_and_clusterpreference.yaml, tests/manifests/vm_with_different_volume_types.yaml, tests/manifests/vm_with_dv_and_dvtemplate.yaml, tests/manifests/vm_with_instancetype_and_preference.yaml, tests/manifests/vm_with_pvc.yaml, tests/utils.go
The .spec.running field is deprecated, therefore we should runStrategy instread.
For more info, look at:
https://github.com/kubevirt/kubevirt/issues/11993
Fixes #
```release-note
NONE
```
=> Remove usage of deprecated .spec.running field

pkg/plugin/vm_backup_item_action.go, pkg/plugin/vm_restore_item_action.go, pkg/plugin/vm_restore_item_action_test.go, pkg/plugin/vmi_backup_item_action.go, pkg/util/util.go, tests/framework/backup.go, tests/vm_backup_test.go
This Pull Request enhances the behavior of VirtualMachine restores by introducing a new label:
"velero.kubevirt.io/restore-run-strategy"
This label can be added to the restore resource to explicitly control the power state of the VirtualMachine during the restore process. The VirtualMachine's state is backed up as it exists at the time of backup, but these labels allow you to override the default behavior and define the desired RunStrategy at restore time.
**Which issue(s) this PR fixes**:
Fixes # https://github.com/kubevirt/kubevirt-velero-plugin/issues/294
There's some overlapping code with https://github.com/kubevirt/kubevirt-velero-plugin/pull/304 but conflicts will be easy to solve. …
=> Allow switching VM power state during restore 

pkg/plugin/vm_backup_item_action.go, pkg/plugin/vm_backup_item_action_test.go, pkg/plugin/vmi_backup_item_action.go, pkg/plugin/vmi_backup_item_action_test.go
Manual backport of https://github.com/kubevirt/kubevirt-velero-plugin/pull/285. Had to address some conflicts with the VM object graph, no major issues during backport.
This is part of the features we want to get into oadp 1.4.2 as discussed offline (related to https://github.com/kubevirt/kubevirt-velero-plugin/issues/199#issuecomment-2518208250).
Fixes #
```release-note
Allow skipping restore-specific checks during backup
```
=> [release-0.7] Allow skipping restore-specific checks during backup

pkg/plugin/vm_restore_item_action.go, pkg/plugin/vmi_restore_item_action.go, pkg/plugin/vmi_restore_item_action_test.go, pkg/util/util.go, pkg/util/util_test.go, tests/framework/backup.go, tests/vm_backup_test.go
When a virtual machine is restored to an alternate namespace, the virtual machine is restored with the same MAC address as the original one. This results in a MAC address conflict if the original virtual machine is still running on the original namespace.
Though we already have a work-in-progress PR, recent interest in this feature has forced us to open a new one to address this issue. From now on, users can optionally clean a VM or VMI MAC address by setting the `"velero.kubevirt.io/clear-mac-address"` label in the restore object.
Cherry-picked a couple of commits from https://github.com/kubevirt/kubevirt-velero-plugin/pull/235 to keep the original contributor's work.
/cc @esteban-ee
**Which issue(s) this PR fixes**:
Fixes #199 …
=> MAC address cleanup

pkg/plugin/vm_restore_item_action.go, pkg/plugin/vmi_restore_item_action.go, pkg/plugin/vmi_restore_item_action_test.go, pkg/util/util.go, pkg/util/util_test.go, tests/framework/backup.go, tests/vm_backup_test.go
This is a manual backport of https://github.com/kubevirt/kubevirt-velero-plugin/pull/304. Had to address some conflicts with the VM object graph code, no major issues.
Fixes #
```release-note
Support clearing MAC address by label
```
=> [release-0.7] MAC address cleanup

pkg/plugin/vmi_backup_item_action.go, pkg/plugin/vmi_backup_item_action_test.go, tests/resource_filtering_test.go
Manual backport of https://github.com/kubevirt/kubevirt-velero-plugin/pull/273. Just needed to remove one duplicate variable declaration.
Fixes # https://issues.redhat.com/browse/CNV-45094
There's enough interest in this bugfix to justify the backport. More context in https://issues.redhat.com/browse/CNV-45094. @ShellyKa13 wdyt? 
```release-note
Bugfix: Ignore VMIs from backup when owner VM is excluded
```
=> [release-v0.7] Ignore VMIs from backup when owner VMs are excluded

Makefile
The permissions for executing the hack/build/build.sh script were not set correctly.
Fixes #
```release-note
NONE
```
=> fix: update permissions for build-all

pkg/plugin/vm_restore_item_action.go, pkg/plugin/vm_restore_item_action_test.go, pkg/plugin/vmi_restore_item_action.go, pkg/util/util.go, tests/vm_backup_test.go
Manual backport of https://github.com/kubevirt/kubevirt-velero-plugin/pull/317, just had to address one conflict in a unit test. 
Fixes # https://github.com/kubevirt/kubevirt-velero-plugin/issues/199#issuecomment-2466301398
```release-note
Add label to optionally generate new firmware UUID during restore
```
=> [release-v0.7] Generate new firmware UUID during restore

.gitignore, tests/manifests/cluster-preference.yaml, tests/manifests/preference.yaml, tests/vm_backup_test.go
This change ensures copies of the original ControllerRevisions are
retained and used to assert that they are referenced by the VM after it
is restored.
The underlying instance type and preference objects are also updated and
further assertions made about the eventual VirtualMachineInstance to
ensure the original revision of these objects is used.
Fixes #
```release-note
NONE
```
=> Improve instance type and preference functional test coverage

go.mod
Update go.mod to support switch from Cachito to Hermeto (Cachi2).
[Replacing Cachito with Hermeto (formerly known as Cachi2)](https://spaces.redhat.com/pages/viewpage.action?pageId=591269742)
While switching should "Just Work" :TM: , it is not always seemless and we've discovered a discrepancy using Hermeto to deliver sources to fail because an attempt is made to download files during hermetic build.
- [Failing scratch build](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=67206344) without change
- [Slack thread (comment)](https://redhat-internal.slack.com/archives/C02AX10EQJW/p1743699832886149?thread_ts=1743628332.968749&cid=C02AX10EQJW)
- [Successful scratch build](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=67228718) with change
=> NO-JIRA: v0.7: go mod tidy

hack/cluster-deploy-prerequisites.sh, tests/framework/framework.go, tests/vm_backup_test.go
Tests using `vmStateStorageClass` may fail downstream in clusters where the default storage class lacks snapshot support. An optimal solution would be to use a default storage class that supports snapshots downstream, as backup and restore functionalities depend on it. That said, attempting to use KV_STORAGE_CLASS and updating the kubevirt spec will fix the issue.
Fixes # https://issues.redhat.com/browse/CNV-57363
```release-note
NONE
```
=> Improve handling of vmStateStorageClass

pkg/plugin/vm_restore_item_action_test.go, pkg/util/kvgraph/backup_graph.go, pkg/util/kvgraph/restore_graph.go, pkg/util/kvgraph/restore_graph_test.go, pkg/util/kvgraph/util.go
In order to restore one or more Virtual Machines out of many  in the SAME namespace, velero offers restoring by resource label.
When using a label selector, any resource not including the restore label are excluded by velero.
That might include other resources that are quieted for the VM, such as datavolumes and PVCs.
In order to resolve this,  we already  include any additional required resource in a graph which is return to velero for backup/restore even if those resources do not include matching label.
With this PR we are removing a condition results in excluding PVC for datavolume type VM volume from the graph, and a the datavolume pending for ever for the existence of the associated PVC after restore.
fixes issue: https://issues.redhat.com/browse/OADP-5608
How to test?
Deploy  the …
=> Do not skip PVC when building VMIs resaources graph during restore item action.

pkg/util/kvgraph/util.go
- Add handling for cloudInitNoCloud.userDataSecretRef backup
- Add handling for cloudInitNoCloud.networkDataSecretRef backup
- Add handling for cloudInitConfigDrive.userDataSecretRef backup
- Add handling for cloudInitConfigDrive.networkDataSecretRef backup
- De-duplicate added dependent resources inside addVolumeGraph()
- Issue Reference: https://github.com/kubevirt/kubevirt-velero-plugin/issues/358
Fixes #358
=> Fix backup of CloudInit secrets

.gitignore, pkg/plugin/vm_backup_item_action_test.go, pkg/util/kvgraph/backup_graph_test.go, pkg/util/kvgraph/restore_graph_test.go, pkg/util/kvgraph/util.go
These objects do not need to be captured as part of the graph as we
already capture point in time copies within controller revisions that
are already included.
Fixes #
I've also included a tiny chore commit adding `.config` to `.gitignore` after getting frustrated with kubevirtci (?) leftovers being picked up.
```release-note
Instance type and preference referenced by a VirtualMachine objects are no longer captured and restored by the plugin. Only the required ControllerRevision copies of these objects are captured and restored avoiding any …
```
=> kvgraph: Remove instance type and preference objects from graph
